project:
  poster: posters/

spring:
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/java-back
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

base:
  url: "http://localhost:8080"