spring:
  datasource:
    username: postgres
    password: A28060550946
    url: jdbc:postgresql://localhost:5432/java-final
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true